CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ORYX_ENABLE = yes
OPT_DEFS += -DHOLD_ON_OTHER_KEY_PRESS_PER_KEY
OS_DETECTION_ENABLE = yes
RGB_MATRIX_CUSTOM_KB = yes
SPACE_CADET_ENABLE = no
REPEAT_KEY_ENABLE = yes
